import type { Metadata } from "next";
import { ArrowLeft, ArrowRight, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CtaBand } from "@/components/cta-band";
import { DoorVisual } from "@/components/door-visual";
import { formatPrice, getCategoryBySlug, getProducts } from "@/lib/catalog";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const slug = (await params).slug; const category = await getCategoryBySlug(slug); return category ? { title: category.name, description: category.description, alternates: { canonical: `/danh-muc/${slug}` }, openGraph: { title: category.name, description: category.description, images: ["/og.png"] }, twitter: { card: "summary_large_image", title: category.name, description: category.description, images: ["/og.png"] } } : {}; }
export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) { const slug = (await params).slug; const [category, products] = await Promise.all([getCategoryBySlug(slug), getProducts({ category: slug })]); if (!category) notFound(); return <><section className="detail-hero"><div className="container"><Link href="/san-pham" className="back-link"><ArrowLeft /> Toàn bộ sản phẩm</Link><span className="kicker">Danh mục sản phẩm</span><h1>{category.name}</h1><p>{category.description}</p></div></section><section className="section"><div className="container">{products.length ? <div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><Link href={`/san-pham/${product.slug}`} className="product-image-link" aria-label={`Xem chi tiết ${product.name}`}><DoorVisual label={category.name} kind="product" accent={product.accent} imageUrl={product.images[0]?.url} imageAlt={product.name} /></Link><div className="product-card-body"><span className="product-category">{category.name}</span><h2>{product.name}</h2><p>{product.shortDescription}</p><div className="product-footer"><span><ShieldCheck /> {product.warranty}</span><b>{formatPrice(product)}</b></div><Link href={`/san-pham/${product.slug}`} className="text-link">Xem chi tiết <ArrowRight /></Link></div></article>)}</div> : <div className="empty-state"><h2>Danh mục đang được cập nhật</h2><p>Quay lại sau hoặc liên hệ để được tư vấn sản phẩm phù hợp.</p></div>}</div></section><CtaBand compact /></>; }
