import { ArrowUpRight, Boxes, Eye, FilePenLine, FolderTree, ImageIcon, Plus } from "lucide-react";
import Link from "next/link";
import { getAdminOverview, getAdminProducts } from "@/lib/admin-data";
import { isSupabaseConfigured } from "@/lib/supabase-rest";

export default async function AdminDashboardPage() {
  const [overview, products] = await Promise.all([getAdminOverview(), getAdminProducts()]); const demo = !isSupabaseConfigured();
  const cards = [{ label: "Tổng sản phẩm", value: overview.products, icon: Boxes }, { label: "Đang hiển thị", value: overview.published, icon: Eye }, { label: "Bản nháp", value: overview.drafts, icon: FilePenLine }, { label: "Danh mục", value: overview.categories, icon: FolderTree }, { label: "Ảnh đã tải", value: overview.media, icon: ImageIcon }];
  return <><header className="admin-page-header"><div><span>Tổng quan</span><h1>Chào buổi làm việc.</h1><p>Theo dõi nội dung chính và cập nhật catalog từ đây.</p></div><Link href="/admin/products/new" className="button button-primary"><Plus /> Thêm sản phẩm</Link></header><section className="admin-stat-grid">{cards.map(({ label, value, icon: Icon }) => <article key={label}><Icon /><span>{label}</span><b>{value}</b></article>)}</section><section className="admin-panel"><div className="admin-panel-heading"><div><span>Cập nhật gần đây</span><h2>Sản phẩm</h2></div><Link href="/admin/products">Xem tất cả <ArrowUpRight /></Link></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Sản phẩm</th><th>Danh mục</th><th>Trạng thái</th><th>Cập nhật</th></tr></thead><tbody>{products.slice(0,5).map((product) => <tr key={product.id}><td><Link href={`/admin/products/${product.id}`}>{product.name}</Link><small>/{product.slug}</small></td><td>{product.category?.name}</td><td><span className={`status-badge ${product.status}`}>{product.status === "published" ? "Hiển thị" : product.status === "draft" ? "Bản nháp" : "Lưu trữ"}</span></td><td>{demo ? "Dữ liệu mẫu" : new Date(product.updated_at).toLocaleDateString("vi-VN")}</td></tr>)}</tbody></table></div></section>{demo && <section className="admin-panel setup-panel" id="setup"><span className="kicker">Kích hoạt CMS</span><h2>Ba bước để bắt đầu lưu dữ liệu</h2><ol><li><b>01</b><span>Tạo project Supabase và chạy file migration trong SQL Editor.</span></li><li><b>02</b><span>Tạo người dùng Admin, sau đó chạy `supabase/ADMIN_SETUP.sql`.</span></li><li><b>03</b><span>Điền URL và Publishable Key vào `.env.local`, rồi khởi động lại website.</span></li></ol></section>}</>;
}
