import type { Metadata } from "next";
import { ArrowLeft, Check, MessageCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CtaBand } from "@/components/cta-band";
import { DoorVisual } from "@/components/door-visual";
import { formatPrice, getProductBySlug, getProducts, getSiteSettings } from "@/lib/catalog";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const product = await getProductBySlug((await params).slug); if (!product) return {}; const image = product.images[0]?.url; return { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription, openGraph: { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription, images: image ? [{ url: image, alt: product.images[0]?.altText || product.name }] : [] }, twitter: { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription, images: image ? [image] : [] } }; }

export default async function ProductDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug; const product = await getProductBySlug(slug); if (!product) notFound();
  const [site, related] = await Promise.all([getSiteSettings(), getProducts({ category: product.category.slug })]);
  const relatedProducts = related.filter((item) => item.id !== product.id).slice(0, 3);
  return <><section className="detail-hero"><div className="container detail-hero-grid"><div><Link href="/san-pham" className="back-link"><ArrowLeft /> Tất cả sản phẩm</Link><Link href={`/danh-muc/${product.category.slug}`} className="kicker">{product.category.name}</Link><h1>{product.name}</h1><p>{product.shortDescription}</p>{formatPrice(product) && <div className="detail-price">{formatPrice(product)}</div>}<a href={site.zaloHref} className="button button-primary" target="_blank" rel="noreferrer"><MessageCircle /> Nhận tư vấn</a></div><DoorVisual label={product.category.name} kind="product" accent={product.accent} imageUrl={product.images[0]?.url} imageAlt={product.images[0]?.altText || product.name} /></div></section>
    <section className="section"><div className="container detail-content-grid"><div><h2>Thông tin sản phẩm</h2><p className="product-description">{product.description || product.shortDescription}</p><h2>Thông số kỹ thuật</h2>{product.specs.length ? <ul className="spec-table">{product.specs.map((item) => <li key={item.id}><span>{item.name}</span><b>{item.value}</b></li>)}</ul> : <p className="muted-copy">Thông số đang được cập nhật. Vui lòng liên hệ để được tư vấn theo model thực tế.</p>}<div className="content-note"><ShieldCheck /><p><b>Bảo hành dự kiến: {product.warranty}.</b><br />Model, thông số và chính sách chính thức được xác nhận tại thời điểm tư vấn.</p></div></div><aside className="quote-card"><span>Tư vấn trước khi lắp</span><h3>Thiết bị cần phù hợp tải và hệ điều khiển hiện có.</h3><p>Gửi ảnh motor, hộp nhận hoặc kích thước cửa để được tư vấn sơ bộ.</p><Link href="/lien-he#dat-lich" className="button button-dark">Gửi thông tin thiết bị</Link></aside></div></section>
    {relatedProducts.length > 0 && <section className="section section-tint"><div className="container"><div className="section-heading"><span className="kicker">Cùng danh mục</span><h2>Sản phẩm liên quan</h2></div><div className="home-product-grid">{relatedProducts.map((item) => <article className="home-product-card" key={item.id}><DoorVisual label={item.category.name} kind="product" accent={item.accent} imageUrl={item.images[0]?.url} imageAlt={item.name} /><div><span className="product-category">{item.category.name}</span><h3>{item.name}</h3><p>{item.shortDescription}</p><div><b>{formatPrice(item)}</b><Link href={`/san-pham/${item.slug}`} aria-label={`Xem ${item.name}`}><ArrowLeft className="rotate-180" /></Link></div></div></article>)}</div></div></section>}<CtaBand compact /></>;
}
