import { getAdminAccessToken } from "@/lib/admin-auth";
import { getCategories, getHomepageContent, getProducts, getSiteSettings } from "@/lib/catalog";
import { getSupabaseConfig, supabaseFetch } from "@/lib/supabase-rest";

export type AdminCategoryRow = { id: string; name: string; slug: string; description: string | null; image_path: string | null; sort_order: number; is_active: boolean };
export type AdminImageRow = { id: string; storage_path: string; alt_text: string | null; sort_order: number; is_primary: boolean };
export type AdminSpecRow = { id: string; spec_name: string; spec_value: string; group_name: string | null; sort_order: number };
export type AdminProductRow = { id: string; category_id: string; name: string; slug: string; short_description: string | null; description: string | null; price_mode: string; price_amount: number | null; price_label: string | null; currency: string; warranty: string | null; is_featured: boolean; status: string; sort_order: number; seo_title: string | null; seo_description: string | null; accent: string | null; updated_at: string; category?: { name: string; slug: string }; images?: AdminImageRow[]; specs?: AdminSpecRow[] };
export type MediaRow = { id: string; storage_path: string; file_name: string; alt_text: string | null; mime_type: string; size_bytes: number; created_at: string };

export async function getAdminCategories() { if (!getSupabaseConfig()) return (await getCategories()).map((x) => ({ id: x.id, name: x.name, slug: x.slug, description: x.description, image_path: x.imagePath || null, sort_order: x.sortOrder, is_active: true })); const token = await getAdminAccessToken(); return supabaseFetch<AdminCategoryRow[]>("/rest/v1/categories?select=*&order=sort_order.asc,created_at.desc", { cache: "no-store" }, token); }
export async function getAdminProducts() { if (!getSupabaseConfig()) return (await getProducts()).map((x) => ({ id: x.id, category_id: x.category.id, name: x.name, slug: x.slug, short_description: x.shortDescription, description: x.description, price_mode: x.priceMode, price_amount: x.priceAmount, price_label: x.priceLabel, currency: x.currency, warranty: x.warranty, is_featured: x.featured, status: x.status, sort_order: 0, seo_title: x.seoTitle, seo_description: x.seoDescription, accent: x.accent, updated_at: new Date().toISOString(), category: { name: x.category.name, slug: x.category.slug }, images: x.images.map((i) => ({ id: i.id, storage_path: i.storagePath, alt_text: i.altText, sort_order: i.sortOrder, is_primary: i.isPrimary })), specs: x.specs.map((s) => ({ id: s.id, spec_name: s.name, spec_value: s.value, group_name: s.groupName, sort_order: s.sortOrder })) })); const token = await getAdminAccessToken(); return supabaseFetch<AdminProductRow[]>("/rest/v1/products?select=id,category_id,name,slug,short_description,price_mode,price_amount,price_label,currency,warranty,is_featured,status,sort_order,seo_title,seo_description,accent,updated_at,category:categories(name,slug)&order=updated_at.desc", { cache: "no-store" }, token); }
export async function getAdminProduct(id: string) { if (!getSupabaseConfig()) return (await getAdminProducts()).find((item) => item.id === id) || null; const token = await getAdminAccessToken(); const rows = await supabaseFetch<AdminProductRow[]>(`/rest/v1/products?select=*,category:categories(name,slug),images:product_images(*),specs:product_specs(*)&id=eq.${encodeURIComponent(id)}&limit=1`, { cache: "no-store" }, token); return rows[0] || null; }
export async function getAdminMedia() { if (!getSupabaseConfig()) return []; const token = await getAdminAccessToken(); return supabaseFetch<MediaRow[]>("/rest/v1/media_assets?select=*&order=created_at.desc&limit=100", { cache: "no-store" }, token); }
export async function getAdminSettings() { if (!getSupabaseConfig()) { const x = await getSiteSettings(); return { company_name: x.name, short_name: x.shortName, site_description: x.description, hotline: x.hotline, zalo_url: x.zaloHref, email: x.email, address: x.address, facebook_url: x.facebookHref, messenger_url: x.messengerHref, maps_url: x.mapsHref, business_hours: x.hours, service_area: x.serviceArea }; } const token = await getAdminAccessToken(); const rows = await supabaseFetch<Array<Record<string,string | null>>>("/rest/v1/site_settings?id=eq.main&select=*&limit=1", { cache: "no-store" }, token); return rows[0] || {}; }
export async function getAdminHomepage() { if (!getSupabaseConfig()) { const x = await getHomepageContent(); return { hero_eyebrow: x.heroEyebrow, hero_title: x.heroTitle, hero_emphasis: x.heroEmphasis, hero_description: x.heroDescription, hero_cta_label: x.heroCtaLabel, intro_title: x.introTitle, intro_text: x.introText }; } const token = await getAdminAccessToken(); const rows = await supabaseFetch<Array<Record<string,string | null>>>("/rest/v1/homepage_content?id=eq.main&select=*&limit=1", { cache: "no-store" }, token); return rows[0] || {}; }
export async function getAdminOverview() {
  if (!getSupabaseConfig()) { const [products, categories] = await Promise.all([getProducts(), getCategories()]); return { products: products.length, published: products.filter((item) => item.status === "published").length, drafts: 0, categories: categories.length, media: 0 }; }
  const token = await getAdminAccessToken();
  const [products, categories, media] = await Promise.all([
    supabaseFetch<Array<{ status: string }>>("/rest/v1/products?select=status", { cache: "no-store" }, token),
    supabaseFetch<Array<{ id: string }>>("/rest/v1/categories?select=id", { cache: "no-store" }, token),
    supabaseFetch<Array<{ id: string }>>("/rest/v1/media_assets?select=id", { cache: "no-store" }, token),
  ]);
  return { products: products.length, published: products.filter((item) => item.status === "published").length, drafts: products.filter((item) => item.status === "draft").length, categories: categories.length, media: media.length };
}
