import { Save, Upload } from "lucide-react";
import { saveProduct } from "@/lib/admin-actions";
import type { AdminCategoryRow, AdminProductRow } from "@/lib/admin-data";
import { publicAssetUrl } from "@/lib/supabase-rest";
import { deleteProductImage } from "@/lib/admin-actions";

export function AdminProductForm({ product, categories, demo }: { product?: AdminProductRow | null; categories: AdminCategoryRow[]; demo: boolean }) {
  const specs = (product?.specs || []).sort((a,b) => a.sort_order-b.sort_order).map((item) => `${item.spec_name}|${item.spec_value}`).join("\n");
  return <form action={saveProduct} className="admin-form"><input type="hidden" name="id" value={product?.id || ""} /><input type="hidden" name="has_images" value={product?.images?.length ? "yes" : "no"} />
    <section className="admin-form-card"><div className="admin-form-section-title"><div><span>Thông tin chính</span><h2>{product ? "Chỉnh sửa sản phẩm" : "Thêm sản phẩm mới"}</h2></div><label className="status-field"><span>Trạng thái</span><select name="status" defaultValue={product?.status || "published"}><option value="published">Đang hiển thị trên website</option><option value="draft">Bản nháp (không hiện)</option><option value="archived">Đã lưu trữ (không hiện)</option></select><small>Chỉ trạng thái “Đang hiển thị” mới xuất hiện ngoài website.</small></label></div><div className="admin-fields two"><label><span>Tên sản phẩm *</span><input required name="name" defaultValue={product?.name || ""} /></label><label><span>Slug</span><input name="slug" defaultValue={product?.slug || ""} placeholder="Tự tạo từ tên nếu bỏ trống" /></label><label><span>Danh mục *</span><select required name="category_id" defaultValue={product?.category_id || ""}><option value="">Chọn danh mục</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label><span>Bảo hành</span><input name="warranty" defaultValue={product?.warranty || ""} placeholder="Ví dụ: 24 tháng" /></label><label className="full"><span>Mô tả ngắn</span><textarea name="short_description" rows={3} defaultValue={product?.short_description || ""} /></label><label className="full"><span>Mô tả chi tiết</span><textarea name="description" rows={7} defaultValue={product?.description || ""} /></label></div></section>
    <section className="admin-form-card"><div className="admin-form-section-title"><div><span>Giá & hiển thị</span><h2>Cách trình bày trên catalog</h2></div></div><div className="admin-fields four"><label><span>Kiểu giá</span><select name="price_mode" defaultValue={product?.price_mode || "contact"}><option value="exact">Giá chính xác</option><option value="from">Giá từ</option><option value="contact">Liên hệ</option><option value="hidden">Ẩn giá</option></select></label><label><span>Số tiền</span><input name="price_amount" inputMode="numeric" defaultValue={product?.price_amount || ""} /></label><label><span>Nhãn thay thế</span><input name="price_label" defaultValue={product?.price_label || ""} placeholder="Liên hệ / Theo kích thước" /></label><label><span>Màu thẻ</span><input name="accent" type="color" defaultValue={product?.accent || "#b9f5dc"} /></label><label><span>Thứ tự</span><input name="sort_order" type="number" defaultValue={product?.sort_order || 0} /></label><label className="check-field"><input type="checkbox" name="is_featured" defaultChecked={product?.is_featured} /><span>Sản phẩm nổi bật</span></label></div></section>
    <section className="admin-form-card"><div className="admin-form-section-title"><div><span>Thông số</span><h2>Mỗi dòng một thông số</h2><p>Dùng định dạng: Tên thông số | Giá trị</p></div></div><label className="admin-block-field"><textarea name="specs" rows={8} defaultValue={specs} placeholder={'Tải trọng | 500 kg\nNguồn điện | 220V\nBảo hành | 24 tháng'} /></label></section>
    <section className="admin-form-card"><div className="admin-form-section-title"><div><span>Hình ảnh</span><h2>Ảnh đại diện và gallery</h2><p>JPG, PNG hoặc WebP; tối đa 5MB/ảnh.</p></div></div>{product?.images?.length ? <div className="admin-image-grid">{product.images.map((image) => { const removeImage = deleteProductImage.bind(null, product.id, image.id, image.storage_path); return <div key={image.id}><img src={publicAssetUrl(image.storage_path) || ""} alt={image.alt_text || product.name} /><button type="submit" formAction={removeImage} disabled={demo}>Xóa ảnh</button></div>; })}</div> : null}<label className="admin-upload"><Upload /><span>Chọn tối đa 6 ảnh</span><input type="file" name="images" accept="image/jpeg,image/png,image/webp" multiple disabled={demo} /></label></section>
    <section className="admin-form-card"><div className="admin-form-section-title"><div><span>SEO</span><h2>Hiển thị trên công cụ tìm kiếm</h2></div></div><div className="admin-fields"><label><span>SEO Title</span><input name="seo_title" maxLength={65} defaultValue={product?.seo_title || ""} /></label><label><span>SEO Description</span><textarea name="seo_description" maxLength={170} rows={3} defaultValue={product?.seo_description || ""} /></label></div></section>
    <div className="admin-sticky-save"><span>{demo ? "Kết nối Supabase để lưu thay đổi." : "Thay đổi sẽ xuất hiện sau khi lưu."}</span><button className="button button-primary" disabled={demo}><Save /> Lưu sản phẩm</button></div>
  </form>;
}
